name: blinky_bridge
topics:
  /blinky/map_wire_z:
    type: std_msgs/msg/UInt8MultiArray
    from_domain: 5
    to_domain: 90
  /blinky/nav2_collision_ahead:
    type: std_msgs/msg/Bool
    from_domain: 5
    to_domain: 90
  /blinky/nav2_retrace_active:
    type: std_msgs/msg/Bool
    from_domain: 5
    to_domain: 90
  /blinky/map:
    type: nav_msgs/msg/OccupancyGrid
    from_domain: 5
    to_domain: 90
  /blinky/tf:
    type: tf2_msgs/msg/TFMessage
    from_domain: 5
    to_domain: 90
  /blinky/tf_static:
    type: tf2_msgs/msg/TFMessage
    from_domain: 5
    to_domain: 90
  /blinky/navigate_to_pose/_action/status:
    type: action_msgs/msg/GoalStatusArray
    from_domain: 5
    to_domain: 90
  /blinky/navigate_to_pose/_action/feedback:
    type: nav2_msgs/action/NavigateToPose_FeedbackMessage
    from_domain: 5
    to_domain: 90
  /blinky/navigate_to_pose/_action/result:
    type: nav2_msgs/action/NavigateToPose_Result
    from_domain: 5
    to_domain: 90
  /blinky/compute_path_to_pose/_action/status:
    type: action_msgs/msg/GoalStatusArray
    from_domain: 5
    to_domain: 90
  /blinky/compute_path_to_pose/_action/feedback:
    type: nav2_msgs/action/ComputePathToPose_FeedbackMessage
    from_domain: 5
    to_domain: 90
  /blinky/compute_path_to_pose/_action/result:
    type: nav2_msgs/action/ComputePathToPose_Result
    from_domain: 5
    to_domain: 90
