name: pinky_bridge
topics:
  /pinky/map_wire_z:
    type: std_msgs/msg/UInt8MultiArray
    from_domain: 22
    to_domain: 90
  /pinky/nav2_collision_ahead:
    type: std_msgs/msg/Bool
    from_domain: 22
    to_domain: 90
  /pinky/nav2_retrace_active:
    type: std_msgs/msg/Bool
    from_domain: 22
    to_domain: 90
  /pinky/map:
    type: nav_msgs/msg/OccupancyGrid
    from_domain: 22
    to_domain: 90
  /pinky/tf:
    type: tf2_msgs/msg/TFMessage
    from_domain: 22
    to_domain: 90
  /pinky/tf_static:
    type: tf2_msgs/msg/TFMessage
    from_domain: 22
    to_domain: 90
  /pinky/navigate_to_pose/_action/status:
    type: action_msgs/msg/GoalStatusArray
    from_domain: 22
    to_domain: 90
  /pinky/navigate_to_pose/_action/feedback:
    type: nav2_msgs/action/NavigateToPose_FeedbackMessage
    from_domain: 22
    to_domain: 90
  /pinky/navigate_to_pose/_action/result:
    type: nav2_msgs/action/NavigateToPose_Result
    from_domain: 22
    to_domain: 90
  /pinky/compute_path_to_pose/_action/status:
    type: action_msgs/msg/GoalStatusArray
    from_domain: 22
    to_domain: 90
  /pinky/compute_path_to_pose/_action/feedback:
    type: nav2_msgs/action/ComputePathToPose_FeedbackMessage
    from_domain: 22
    to_domain: 90
  /pinky/compute_path_to_pose/_action/result:
    type: nav2_msgs/action/ComputePathToPose_Result
    from_domain: 22
    to_domain: 90
